analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#ded3d9'
    - '#6c4943'
    - '#d26638'
    - '#2b1917'
  brandStrength: 0.6875
  lightness: 0.625
  rhythmicContrast: 1
  saturation: 0.375
cta: {}
layout_spectrum: 0.203828
name: Polemicist
opengraph: {}
purpose: []
title: 'The scientific polemicist. '
typography_spectrum: 0.91727
