name: polemicist
favicon: null
layout_spectrum: 0.8181150862947106
typography_spectrum: 0.5657469800207764
title: 'The scientific polemicist. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.42466735537163913
  lightness: 0.6329973542597145
  saturation: 0.02759606041945517
  rhythmicContrast: 0.5838294341228902
purpose: []
