name: Polemicist
favicon: null
layout_spectrum: 0.8181150862947106
typography_spectrum: 0.5657469800207764
title: 'The scientific polemicist. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ded3d9'
    - '#6c4943'
    - '#d26638'
    - '#2b1917'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
